# Generated by Django 5.1.7 on 2025-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movierating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
