# Generated by Django 5.1.7 on 2025-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0002_movierating_created_at_movierating_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Gujarati', 'Gujarati'), ('Punjabi', 'Punjabi'), ('Urdu', 'Urdu'), ('Malayalam', 'Malayalam'), ('Others', 'Others')], help_text='Primary language of the movie', max_length=50),
        ),
    ]
